[package]
name = "hyperdb-cli"
version = "0.1.1"
edition = "2021"
authors = ["Afaan Bilal <hello@afaan.dev>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
hyperdb-rs = "0.1.0"
